services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 9090:8080
    environment:
      MYSQL_HOST: mysqldb-linked
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb-linked:
    container_name: mysqldb-linked
    image: mysql
    #volumes:
     # -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: company_organization
      MYSQL_ROOT_PASSWORD: root
        
